### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by lefromage** [Piezoid/pugz#12]
trying to decompress or count lines of compressed tab separated files

~/git/pugz/gunzip -l file.tsv.gz 

terminate called after throwing an instance of 'gzip_error'
  what():  INVALID_LITERAL
Aborted (core dumped)

**Comment by lefromage** [comment]
the problem is probably due to this (found in README)

Only text files with ASCII characters in the range ['\t', '~'] are supported.

**Comment by rchikhi** [comment]
hi yes, is it a ASCII file?
